# Generated by Django 4.2.1 on 2023-06-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Zhichani', 'Zhichani'), ('Duvachki', 'Duvachki'), ('UDARNI', 'Udarni'), ('Klavijatura', 'Klavijatura')], default='Zhichani', max_length=11)),
                ('type', models.CharField(max_length=1)),
                ('manufacturer', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
