# Generated by Django 4.2.1 on 2023-06-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_instrument_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='category',
            field=models.CharField(choices=[('Zhichani', 'Жичани'), ('Duvachki', 'Duvachki'), ('Udarni', 'Udarni'), ('Klavijatura', 'Klavijatura')], default='Zhichani', max_length=11),
        ),
    ]
