# Generated by Django 4.2.1 on 2023-06-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('municipality', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('paymenttype', models.CharField(choices=[('Cash', 'Во готово'), ('Credit', 'Со кредитна картичка'), ('Bank', 'Преку банкарска трансакција')], default='Cash', max_length=10)),
                ('cardholdername', models.CharField(blank=True, max_length=50, null=True)),
                ('cardnumber', models.CharField(blank=True, max_length=16, null=True)),
                ('cardexpiry', models.CharField(blank=True, max_length=5, null=True)),
                ('cardcvv', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='instrument',
            name='category',
            field=models.CharField(choices=[('Zhichani', 'Жичани'), ('Duvachki', 'Дувачки'), ('Udarni', 'Ударни'), ('Klavijatura', 'Клавијатура')], default='Zhichani', max_length=11),
        ),
    ]
