# Generated by Django 4.2.1 on 2023-06-23 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='totalprice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
