# Generated by Django 4.2.1 on 2023-06-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_reciept'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciept',
            name='session',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
