# Generated by Django 4.2.1 on 2023-06-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_order_products_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='discountpercent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
